//GENERAL CONSTANTS
export const CLEAR_STORE = "CLEAR_STORE";
export const LOADING = "LOADING";
export const LOGGED_IN = "LOGGED_IN";
export const CHECKING_TOKEN = "CHECKING_TOKEN";

//ADMIN CONSTANTS
export const LOAD_TEACHERLIST = "LOAD_TEACHERLIST";
export const LOAD_BATCHLIST = "LOAD_BATCHLIST";
