//GENERAL CONSTANTS
export const CLEAR_STORE = "CLEAR_STORE";
export const LOADING = "LOADING";
export const LOGGED_IN = "LOGGED_IN";
export const CHECKING_TOKEN = "CHECKING_TOKEN";

//ADMIN CONSTANTS
export const LOAD_PROGRAMLIST = "LOAD_PROGRAMLIST";
export const LOAD_BATCHLIST = "LOAD_BATCHLIST";
export const LOAD_SECTIONLIST = "LOAD_SECTIONLIST";
export const LOAD_COURSELIST = "LOAD_COURSELIST";
export const LOAD_TEACHERLIST = "LOAD_TEACHERLIST";
export const LOAD_TEACHERLIST_TOTAL = "LOAD_TEACHERLIST_TOTAL";
export const LOAD_TEACHERLIST_PAGE = "LOAD_TEACHERLIST_PAGE";
export const LOAD_TEACHERLIST_PAGESIZE = "LOAD_TEACHERLIST_PAGESIZE";
